### ISSUE TITLE
Python 3.6 runtime is no longer available

### ISSUE THREAD

**Issue by johnwalicki** [upkarlidder/coffee-donut-instructions#1]
Importing this Watson Studio project sets up a notebook with a Python 3.6 runtime.  The Python 3.6 runtime no longer exists in Watson Studio as a option.  As a result, the notebook will open but it can't start a kernel to run.

We need to bump this notebook to run in a Python 3.7 runtime.  It works successfully.

Don't choose a Python 3.8 runtime because the `pip install tensorflow==1.15` is not available/compatible with Python 3.8.

**Comment by johnwalicki** [comment]
I exported the project using a `Default Python 3.7 XXS (1 vCPU 4GB RAM)` runtime so that it will execute in an IBM Cloud Lite account.  I have a replacement coffee-donut.zip

Will import / test again and then open a PR

**Comment by johnwalicki** [comment]
@upkarlidder  This PR is necessary to support the IBM booth demo at Open Source Summit this week. Can you merge?

**Comment by upkarlidder** [comment]
Absolutely. I will merge this afternoon. Thank you.

**Comment by johnwalicki** [comment]
Thanks @upkarlidder  - Tonight / tomorrow, I might have additional PRs to update the VCPI shorturl and a few Watson Studio screenshots that have changed.
